# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      replicas: 3
      containers:
      - name: python-app
        image: darshill143/test_repo/:py1
        ports:
        - containerPort: 5000
